
require("./ModernCollabFooter.module.css");
const styles = {
  modernFooter: 'modernFooter_e9e7b3a7',
  slideInFromBottom: 'slideInFromBottom_e9e7b3a7',
  footerContainer: 'footerContainer_e9e7b3a7',
  footerLayout: 'footerLayout_e9e7b3a7',
  linksSection: 'linksSection_e9e7b3a7',
  actionsSection: 'actionsSection_e9e7b3a7',
  compactActions: 'compactActions_e9e7b3a7',
  compactButton: 'compactButton_e9e7b3a7',
  bannerSmall: 'bannerSmall_e9e7b3a7',
  buttonIcon: 'buttonIcon_e9e7b3a7',
  linkPill: 'linkPill_e9e7b3a7',
  linkItem: 'linkItem_e9e7b3a7',
  searchBox: 'searchBox_e9e7b3a7',
  searchArea: 'searchArea_e9e7b3a7',
  searchResults: 'searchResults_e9e7b3a7',
  bannerLarge: 'bannerLarge_e9e7b3a7',
  notificationBar: 'notificationBar_e9e7b3a7',
  contentArea: 'contentArea_e9e7b3a7',
  linksContainer: 'linksContainer_e9e7b3a7',
  linkIcon: 'linkIcon_e9e7b3a7',
  linkBadge: 'linkBadge_e9e7b3a7',
  new: 'new_e9e7b3a7',
  updated: 'updated_e9e7b3a7',
  popular: 'popular_e9e7b3a7',
  urgent: 'urgent_e9e7b3a7',
  pulse: 'pulse_e9e7b3a7',
  pillSquare: 'pillSquare_e9e7b3a7',
  pillMinimal: 'pillMinimal_e9e7b3a7',
  pillRounded: 'pillRounded_e9e7b3a7',
  densityCompact: 'densityCompact_e9e7b3a7',
  densitySpacious: 'densitySpacious_e9e7b3a7',
  densityNormal: 'densityNormal_e9e7b3a7',
  categoryDropdowns: 'categoryDropdowns_e9e7b3a7',
  categoryGroup: 'categoryGroup_e9e7b3a7',
  categoryLabel: 'categoryLabel_e9e7b3a7',
  categoryLinks: 'categoryLinks_e9e7b3a7',
  showMoreIndicator: 'showMoreIndicator_e9e7b3a7',
  dropdownContainer: 'dropdownContainer_e9e7b3a7',
  iconSizeSmall: 'iconSizeSmall_e9e7b3a7',
  icon: 'icon_e9e7b3a7',
  pillIcon: 'pillIcon_e9e7b3a7',
  iconSizeMedium: 'iconSizeMedium_e9e7b3a7',
  iconSizeLarge: 'iconSizeLarge_e9e7b3a7'
};

export default styles;
