
require("./PillDropdown.module.css");
const styles = {
  pill: 'pill_4fde5cfc',
  pillSquare: 'pillSquare_4fde5cfc',
  pillMinimal: 'pillMinimal_4fde5cfc',
  pillRounded: 'pillRounded_4fde5cfc',
  densityCompact: 'densityCompact_4fde5cfc',
  densitySpacious: 'densitySpacious_4fde5cfc',
  densityNormal: 'densityNormal_4fde5cfc',
  open: 'open_4fde5cfc',
  chevron: 'chevron_4fde5cfc',
  active: 'active_4fde5cfc',
  category: 'category_4fde5cfc',
  organization: 'organization_4fde5cfc',
  personal: 'personal_4fde5cfc',
  pillContent: 'pillContent_4fde5cfc',
  pillIcon: 'pillIcon_4fde5cfc',
  pillText: 'pillText_4fde5cfc',
  pillBadge: 'pillBadge_4fde5cfc',
  pulse: 'pulse_4fde5cfc',
  dropdownPortal: 'dropdownPortal_4fde5cfc',
  dropdownContainer: 'dropdownContainer_4fde5cfc',
  dropdown: 'dropdown_4fde5cfc',
  slideInUp: 'slideInUp_4fde5cfc',
  dropdownHeader: 'dropdownHeader_4fde5cfc',
  dropdownTitle: 'dropdownTitle_4fde5cfc',
  dropdownIcon: 'dropdownIcon_4fde5cfc',
  dropdownTitleText: 'dropdownTitleText_4fde5cfc',
  itemCount: 'itemCount_4fde5cfc',
  dropdownContent: 'dropdownContent_4fde5cfc',
  itemsList: 'itemsList_4fde5cfc',
  dropdownItem: 'dropdownItem_4fde5cfc',
  categoriesList: 'categoriesList_4fde5cfc',
  multiLevelList: 'multiLevelList_4fde5cfc',
  categorySection: 'categorySection_4fde5cfc',
  categoryHeader: 'categoryHeader_4fde5cfc',
  expanded: 'expanded_4fde5cfc',
  categoryHeaderContent: 'categoryHeaderContent_4fde5cfc',
  categoryChevron: 'categoryChevron_4fde5cfc',
  categoryBadge: 'categoryBadge_4fde5cfc',
  categorySelector: 'categorySelector_4fde5cfc',
  categoryInfo: 'categoryInfo_4fde5cfc',
  chevronRight: 'chevronRight_4fde5cfc',
  nestedItemsList: 'nestedItemsList_4fde5cfc',
  nestedHeader: 'nestedHeader_4fde5cfc',
  backButton: 'backButton_4fde5cfc',
  chevronLeft: 'chevronLeft_4fde5cfc',
  selectedCategoryTitle: 'selectedCategoryTitle_4fde5cfc',
  categoryGroup: 'categoryGroup_4fde5cfc',
  categoryTitle: 'categoryTitle_4fde5cfc',
  categoryCount: 'categoryCount_4fde5cfc',
  categoryItems: 'categoryItems_4fde5cfc',
  categoryItem: 'categoryItem_4fde5cfc',
  itemIcon: 'itemIcon_4fde5cfc',
  icon: 'icon_4fde5cfc',
  customIcon: 'customIcon_4fde5cfc',
  itemContent: 'itemContent_4fde5cfc',
  itemTitle: 'itemTitle_4fde5cfc',
  itemDescription: 'itemDescription_4fde5cfc',
  mandatoryBadge: 'mandatoryBadge_4fde5cfc'
};

export default styles;
