define([], function() {
  return {
    "Title": "Pie de Colaboración",
    "MyLinks": "Mis Enlaces",
    "EditMyLinks": "Editar Mis Enlaces",
    "MyLinksSaveSuccess": "Mis enlaces se guardaron correctamente",
    "MyLinksSaveFailed": "Error al guardar mis enlaces",
    
    // General
    "Add": "Añadir",
    "Edit": "Editar",
    "Delete": "Eliminar",
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "Close": "Cerrar",
    "Back": "Volver",
    "Search": "Buscar",
    "Loading": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Warning": "Advertencia",
    
    // Link Management
    "ManageLinks": "Gestionar Enlaces",
    "PersonalLinks": "Enlaces Personales",
    "OrganizationLinks": "Enlaces de la Organización",
    "AddPersonalLink": "Añadir Enlace Personal",
    "AddOrganizationLink": "Añadir Enlace de la Organización",
    "EditLink": "Editar Enlace",
    "DeleteLink": "Eliminar Enlace",
    "LinkTitle": "Título",
    "LinkUrl": "URL",
    "LinkDescription": "Descripción",
    "LinkIcon": "Icono",
    "LinkCategory": "Categoría",
    "SearchLinks": "Buscar enlaces...",
    "NoLinksFound": "No se encontraron enlaces",
    "LinkSaved": "Enlace guardado correctamente",
    "LinkDeleted": "Enlace eliminado correctamente",
    "LinkUpdated": "Enlace actualizado correctamente",
    
    // Categories
    "Categories": "Categorías",
    "CategoriesManagement": "Gestión de Categorías",
    "CreateCategory": "Crear Categoría",
    "EditCategory": "Editar Categoría",
    "DeleteCategory": "Eliminar Categoría",
    "CategoryName": "Nombre de la Categoría",
    "CategoryDescription": "Descripción",
    "CategoryColor": "Color",
    "CategoryIcon": "Icono",
    "AllCategories": "Todas las Categorías",
    "General": "General",
    
    // Settings
    "Settings": "Configuración",
    "UserSettings": "Configuración del Usuario",
    "AdminSettings": "Configuración de Administrador",
    "DisplaySettings": "Configuración de Visualización",
    "BehaviorSettings": "Configuración de Comportamiento",
    "PerformanceSettings": "Configuración de Rendimiento",
    
    // Display Options
    "DisplayMode": "Modo de Visualización",
    "FlatPills": "Píldoras Planas",
    "CategoryDropdowns": "Menús de Categorías",
    "TypeBasedDropdowns": "Menús por Tipo",
    "PillStyle": "Estilo de Píldora",
    "Rounded": "Redondeado",
    "Square": "Cuadrado",
    "Minimal": "Mínimo",
    "Density": "Densidad",
    "Compact": "Compacto",
    "Normal": "Normal",
    "Spacious": "Espacioso",
    "ShowIcons": "Mostrar Iconos",
    "ShowBadges": "Mostrar Insignias",
    "IconSize": "Tamaño del Icono",
    "Small": "Pequeño",
    "Medium": "Mediano",
    "Large": "Grande",
    
    // Behavior Options
    "ClickBehavior": "Comportamiento de Clic",
    "OpenInNewTab": "Abrir en Nueva Pestaña",
    "OpenInSameTab": "Abrir en la Misma Pestaña",
    "OpenInPopup": "Abrir en Ventana Emergente",
    "SortOrder": "Orden de Clasificación",
    "Alphabetical": "Alfabético",
    "MostUsedFirst": "Más Usados Primero",
    "RecentlyAddedFirst": "Añadidos Recientemente Primero",
    "ManualOrder": "Orden Manual",
    "MaxVisibleItems": "Elementos Máximos Visibles",
    "EnableAutoCategories": "Habilitar Categorización Automática",
    "EnableQuickAdd": "Habilitar Adición Rápida",
    "EnableGlobalSearch": "Habilitar Búsqueda Global",
    "EnableHoverEffects": "Habilitar Efectos de Hover",
    "EnableKeyboardNavigation": "Habilitar Navegación por Teclado",
    
    // Storage & Sync
    "StorageSync": "Almacenamiento y Sincronización",
    "OneDriveSync": "Sincronización OneDrive",
    "SyncFromOneDrive": "Sincronizar desde OneDrive",
    "SyncToOneDrive": "Sincronizar a OneDrive",
    "SyncFrequency": "Frecuencia de Sincronización",
    "Realtime": "Tiempo Real",
    "Hourly": "Cada Hora",
    "Daily": "Diario",
    "ManualOnly": "Solo Manual",
    "CacheDuration": "Duración del Caché",
    "RecentItemsCount": "Cantidad de Elementos Recientes",
    "EnableAnalytics": "Habilitar Analíticas",
    
    // Admin
    "AdminPanel": "Panel de Administrador",
    "SharePointConfiguration": "Configuración de SharePoint",
    "BulkOperations": "Operaciones Masivas",
    "AnalyticsConfiguration": "Configuración de Analíticas",
    "AnalyticsDashboard": "Panel de Analíticas",
    "AudienceTargeting": "Segmentación de Audiencia",
    "GlobalLinksListTitle": "Título de la Lista de Enlaces Globales",
    "EnableUserSelectionStorage": "Habilitar Almacenamiento de Selección de Usuario",
    "CreateGlobalLinksList": "Crear Lista de Enlaces Globales",
    "CreateUserSelectionsList": "Crear Lista de Selecciones de Usuario",
    "ValidateListsStatus": "Validar Estado de las Listas",
    
    // Import/Export
    "Import": "Importar",
    "Export": "Exportar",
    "ImportSettings": "Importar Configuración",
    "ExportSettings": "Exportar Configuración",
    "ImportLinks": "Importar Enlaces",
    "ExportLinks": "Exportar Enlaces",
    "ResetToDefaults": "Restablecer a Valores Predeterminados",
    "ResetAllSettings": "Restablecer Toda la Configuración",
    "ValidateAllLinks": "Validar Todos los Enlaces",
    
    // Messages
    "SettingsImportSuccess": "Configuración importada correctamente",
    "SettingsExportSuccess": "Configuración exportada correctamente",
    "SettingsResetSuccess": "Configuración restablecida a valores predeterminados",
    "SettingsSaveSuccess": "Configuración guardada correctamente",
    "LinksImportSuccess": "Enlaces importados correctamente",
    "LinksExportSuccess": "Enlaces exportados correctamente",
    "ValidationSuccess": "Validación completada correctamente",
    "ValidationWarning": "Validación completada con advertencias",
    "ValidationError": "Error en la validación",
    "OperationFailed": "Operación fallida",
    "UnauthorizedAccess": "Acceso no autorizado",
    "NetworkError": "Error de red ocurrido",
    
    // Analytics
    "TotalClicks": "Total de Clics",
    "UniqueUsers": "Usuarios Únicos",
    "PopularLinks": "Enlaces Populares",
    "CategoryUsage": "Uso de Categorías",
    "UsageStatistics": "Estadísticas de Uso",
    "ClickAnalytics": "Analíticas de Clics",
    "UserEngagement": "Participación del Usuario",
    "ExportAnalyticsData": "Exportar Datos de Analíticas",
    
    // Validation Messages
    "RequiredField": "Este campo es obligatorio",
    "InvalidUrl": "Por favor ingresa una URL válida",
    "InvalidEmail": "Por favor ingresa una dirección de correo válida",
    "CategoryAlreadyExists": "La categoría ya existe",
    "LinkAlreadyExists": "El enlace ya existe",
    "FieldTooLong": "El campo es demasiado largo",
    "FieldTooShort": "El campo es demasiado corto",
    
    // New Form Strings
    "None": "(Ninguno)",
    "Reset": "Restablecer",
    "NewCategoryName": "Nuevo nombre de categoría",
    "SubCategoryLabel": "Subcategoría (Opcional)",
    "SubCategoryPlaceholder": "Seleccionar subcategoría...",
    "NewSubCategoryName": "Nuevo nombre de subcategoría",
    "CategoryLabel": "Categoría",
    
    // New Admin Strings
    "GlobalLinksListTitleLabel": "Título de la lista de enlaces globales",
    "GlobalLinksListTitleDesc": "Nombre de la lista SharePoint para enlaces globales",
    "OneDriveUserStorageTitle": "Almacenamiento OneDrive del usuario",
    "EnableUserSelectionStorageLabel": "Habilitar almacenamiento de selección de usuario",
    "StoreInOneDrive": "Almacenar en OneDrive",
    "UseSharePointLists": "Usar listas SharePoint",
    "UserSelectionStorageDesc": "Cuando está habilitado, las selecciones de enlaces y preferencias del usuario se almacenan como archivos JSON en su OneDrive para sincronización entre dispositivos.",
    "SharePointListsManagement": "Gestión de listas SharePoint",
    "GlobalLinksListReady": "Lista de enlaces globales lista",
    "UserSelectionsListReady": "Lista de selecciones de usuario lista",
    "LastChecked": "Última verificación:",
    "GlobalLinksListFound": "Lista de enlaces globales: Encontrada",
    "GlobalLinksListMissing": "Lista de enlaces globales: No encontrada",
    "UserSelectionsListFound": "Lista de selecciones de usuario: Encontrada",
    "UserSelectionsListMissing": "Lista de selecciones de usuario: No encontrada",
    
    // Aria Labels
    "OpenUserSettingsPanelAriaLabel": "Abrir panel de configuración de usuario",
    "ManageLinksAriaLabel": "Gestionar enlaces personales y seleccionar enlaces de organización",
    
    // Dynamic Messages
    "ImportedLinksSuccess": "¡{0} enlaces importados exitosamente a la lista SharePoint!",
    "ImportedLinksFailure": "{0} enlaces no pudieron importarse. Por favor revise la consola para más detalles.",
    "CategoryCreatedSuccess": "¡Categoría \"{0}\" creada exitosamente!",
    "CategoryCreationFailure": "Error al crear categoría: {0}"
  };
});