define([], function() {
  return {
    "Title": "Samarbeids-footer",
    "MyLinks": "Mine Lenker",
    "EditMyLinks": "Rediger Mine Lenker",
    "MyLinksSaveSuccess": "Mine lenker har blitt lagret",
    "MyLinksSaveFailed": "Lagring av mine lenker feilet",
    
    // General
    "Add": "Legg til",
    "Edit": "Rediger",
    "Delete": "Slett",
    "Save": "Lagre",
    "Cancel": "Avbryt",
    "Close": "Lukk",
    "Back": "Tilbake",
    "Search": "Søk",
    "Loading": "Laster...",
    "Error": "Feil",
    "Success": "Vellykket",
    "Warning": "Advarsel",
    
    // Link Management
    "ManageLinks": "Behandle Lenker",
    "PersonalLinks": "Personlige Lenker",
    "OrganizationLinks": "Organisasjonslenker",
    "AddPersonalLink": "Legg til Personlig Lenke",
    "AddOrganizationLink": "Legg til Organisasjonslenke",
    "EditLink": "Rediger Lenke",
    "DeleteLink": "Slett Lenke",
    "LinkTitle": "Tittel",
    "LinkUrl": "URL",
    "LinkDescription": "Beskrivelse",
    "LinkIcon": "Ikon",
    "LinkCategory": "Kategori",
    "SearchLinks": "Søk lenker...",
    "NoLinksFound": "Ingen lenker funnet",
    "LinkSaved": "Lenke lagret",
    "LinkDeleted": "Lenke slettet",
    "LinkUpdated": "Lenke oppdatert",
    
    // Categories
    "Categories": "Kategorier",
    "CategoriesManagement": "Kategori-behandling",
    "CreateCategory": "Opprett Kategori",
    "EditCategory": "Rediger Kategori",
    "DeleteCategory": "Slett Kategori",
    "CategoryName": "Kategorinavn",
    "CategoryDescription": "Beskrivelse",
    "CategoryColor": "Farge",
    "CategoryIcon": "Ikon",
    "AllCategories": "Alle Kategorier",
    "General": "Generelt",
    
    // Settings
    "Settings": "Innstillinger",
    "UserSettings": "Brukerinnstillinger",
    "AdminSettings": "Administratorinnstillinger",
    "DisplaySettings": "Visningsinnstillinger",
    "BehaviorSettings": "Atferdsinnstillinger",
    "PerformanceSettings": "Ytelsesinnstillinger",
    
    // Display Options
    "DisplayMode": "Visningsmodus",
    "FlatPills": "Flate Piller",
    "CategoryDropdowns": "Kategori-rullegardin",
    "TypeBasedDropdowns": "Typebaserte Rullegardin",
    "PillStyle": "Pillestil",
    "Rounded": "Avrundet",
    "Square": "Firkantet",
    "Minimal": "Minimalt",
    "Density": "Tetthet",
    "Compact": "Kompakt",
    "Normal": "Normal",
    "Spacious": "Romslig",
    "ShowIcons": "Vis Ikoner",
    "ShowBadges": "Vis Merker",
    "IconSize": "Ikonstørrelse",
    "Small": "Liten",
    "Medium": "Medium",
    "Large": "Stor",
    
    // Behavior Options
    "ClickBehavior": "Klikkatferd",
    "OpenInNewTab": "Åpne i Ny Fane",
    "OpenInSameTab": "Åpne i Samme Fane",
    "OpenInPopup": "Åpne i Popup",
    "SortOrder": "Sorteringsrekkefølge",
    "Alphabetical": "Alfabetisk",
    "MostUsedFirst": "Mest Brukte Først",
    "RecentlyAddedFirst": "Nylig Lagt til Først",
    "ManualOrder": "Manuell Rekkefølge",
    "MaxVisibleItems": "Maksimalt Synlige Elementer",
    "EnableAutoCategories": "Aktiver Automatiske Kategorier",
    "EnableQuickAdd": "Aktiver Rask Tillegging",
    "EnableGlobalSearch": "Aktiver Global Søk",
    "EnableHoverEffects": "Aktiver Hover-effekter",
    "EnableKeyboardNavigation": "Aktiver Tastaturnavigasjon",
    
    // Storage & Sync
    "StorageSync": "Lagring og Synkronisering",
    "OneDriveSync": "OneDrive-synkronisering",
    "SyncFromOneDrive": "Synkroniser fra OneDrive",
    "SyncToOneDrive": "Synkroniser til OneDrive",
    "SyncFrequency": "Synkroniseringsfrekvens",
    "Realtime": "Sanntid",
    "Hourly": "Hver Time",
    "Daily": "Daglig",
    "ManualOnly": "Bare Manuelt",
    "CacheDuration": "Cache-varighet",
    "RecentItemsCount": "Antall Nylige Elementer",
    "EnableAnalytics": "Aktiver Analyser",
    
    // Admin
    "AdminPanel": "Administratorpanel",
    "SharePointConfiguration": "SharePoint-konfigurasjon",
    "BulkOperations": "Masseoperasjoner",
    "AnalyticsConfiguration": "Analysekonfigurasjon",
    "AnalyticsDashboard": "Analyse-dashbord",
    "AudienceTargeting": "Publikumsmålretting",
    "GlobalLinksListTitle": "Global Lenkeliste Tittel",
    "EnableUserSelectionStorage": "Aktiver Brukervalg-lagring",
    "CreateGlobalLinksList": "Opprett Global Lenkeliste",
    "CreateUserSelectionsList": "Opprett Brukervalgsliste",
    "ValidateListsStatus": "Valider Listestatus",
    
    // Import/Export
    "Import": "Importer",
    "Export": "Eksporter",
    "ImportSettings": "Importer Innstillinger",
    "ExportSettings": "Eksporter Innstillinger",
    "ImportLinks": "Importer Lenker",
    "ExportLinks": "Eksporter Lenker",
    "ResetToDefaults": "Tilbakestill til Standard",
    "ResetAllSettings": "Tilbakestill Alle Innstillinger",
    "ValidateAllLinks": "Valider Alle Lenker",
    
    // Messages
    "SettingsImportSuccess": "Innstillinger importert",
    "SettingsExportSuccess": "Innstillinger eksportert",
    "SettingsResetSuccess": "Innstillinger tilbakestilt til standard",
    "SettingsSaveSuccess": "Innstillinger lagret",
    "LinksImportSuccess": "Lenker importert",
    "LinksExportSuccess": "Lenker eksportert",
    "ValidationSuccess": "Validering fullført",
    "ValidationWarning": "Validering fullført med advarsler",
    "ValidationError": "Validering feilet",
    "OperationFailed": "Operasjon feilet",
    "UnauthorizedAccess": "Uautorisert tilgang",
    "NetworkError": "Nettverksfeil oppstod",
    
    // Analytics
    "TotalClicks": "Totale Klikk",
    "UniqueUsers": "Unike Brukere",
    "PopularLinks": "Populære Lenker",
    "CategoryUsage": "Kategoribruk",
    "UsageStatistics": "Bruksstatistikk",
    "ClickAnalytics": "Klikkanalyser",
    "UserEngagement": "Brukerengasjement",
    "ExportAnalyticsData": "Eksporter Analysedata",
    
    // Validation Messages
    "RequiredField": "Dette feltet er påkrevd",
    "InvalidUrl": "Vennligst angi en gyldig URL",
    "InvalidEmail": "Vennligst angi en gyldig e-postadresse",
    "CategoryAlreadyExists": "Kategorien eksisterer allerede",
    "LinkAlreadyExists": "Lenken eksisterer allerede",
    "FieldTooLong": "Feltet er for langt",
    "FieldTooShort": "Feltet er for kort",
    
    // New Form Strings
    "None": "(Ingen)",
    "Reset": "Tilbakestill",
    "NewCategoryName": "Nytt kategorinavn",
    "SubCategoryLabel": "Underkategori (Valgfritt)",
    "SubCategoryPlaceholder": "Velg underkategori...",
    "NewSubCategoryName": "Nytt underkategorinavn",
    "CategoryLabel": "Kategori",
    
    // New Admin Strings
    "GlobalLinksListTitleLabel": "Global Lenkeliste Tittel",
    "GlobalLinksListTitleDesc": "Navn på SharePoint-listen for globale lenker",
    "OneDriveUserStorageTitle": "OneDrive Brukerlagring",
    "EnableUserSelectionStorageLabel": "Aktiver Brukervalg-lagring",
    "StoreInOneDrive": "Lagre i OneDrive",
    "UseSharePointLists": "Bruk SharePoint-lister",
    "UserSelectionStorageDesc": "Når aktivert, lagres brukerens lenkevalg og innstillinger som JSON-filer i deres OneDrive for synkronisering mellom enheter.",
    "SharePointListsManagement": "SharePoint-listestyring",
    "GlobalLinksListReady": "Global Lenkeliste Klar",
    "UserSelectionsListReady": "Brukervalgsliste Klar",
    "LastChecked": "Sist kontrollert:",
    "GlobalLinksListFound": "Global Lenkeliste: Funnet",
    "GlobalLinksListMissing": "Global Lenkeliste: Mangler",
    "UserSelectionsListFound": "Brukervalgsliste: Funnet",
    "UserSelectionsListMissing": "Brukervalgsliste: Mangler",
    
    // Aria Labels
    "OpenUserSettingsPanelAriaLabel": "Åpne brukerinnstillinger-panelet",
    "ManageLinksAriaLabel": "Behandle personlige lenker og velge organisasjonslenker",
    
    // Dynamic Messages
    "ImportedLinksSuccess": "{0} lenker ble importert til SharePoint-listen!",
    "ImportedLinksFailure": "{0} lenker kunne ikke importeres. Sjekk konsollen for detaljer.",
    "CategoryCreatedSuccess": "Kategorien \"{0}\" ble opprettet!",
    "CategoryCreationFailure": "Kunne ikke opprette kategori: {0}"
  };
});
