define([], function() {
  return {
    "Title": "Samenwerkings-footer",
    "MyLinks": "Mijn Links",
    "EditMyLinks": "Bewerk Mijn Links",
    "MyLinksSaveSuccess": "Mijn links zijn succesvol opgeslagen",
    "MyLinksSaveFailed": "Opslaan van mijn links is mislukt",
    
    // General
    "Add": "Toevoegen",
    "Edit": "Bewerken",
    "Delete": "Verwijderen",
    "Save": "Opslaan",
    "Cancel": "Annuleren",
    "Close": "Sluiten",
    "Back": "Terug",
    "Search": "Zoeken",
    "Loading": "Laden...",
    "Error": "Fout",
    "Success": "Succes",
    "Warning": "Waarschuwing",
    
    // Link Management
    "ManageLinks": "Links Beheren",
    "PersonalLinks": "Persoonlijke Links",
    "OrganizationLinks": "Organisatie Links",
    "AddPersonalLink": "Persoonlijke Link Toevoegen",
    "AddOrganizationLink": "Organisatie Link Toevoegen",
    "EditLink": "Link Bewerken",
    "DeleteLink": "Link Verwijderen",
    "LinkTitle": "Titel",
    "LinkUrl": "URL",
    "LinkDescription": "Beschrijving",
    "LinkIcon": "Pictogram",
    "LinkCategory": "Categorie",
    "SearchLinks": "Links zoeken...",
    "NoLinksFound": "Geen links gevonden",
    "LinkSaved": "Link succesvol opgeslagen",
    "LinkDeleted": "Link succesvol verwijderd",
    "LinkUpdated": "Link succesvol bijgewerkt",
    
    // Categories
    "Categories": "Categorieën",
    "CategoriesManagement": "Categorie Beheer",
    "CreateCategory": "Categorie Aanmaken",
    "EditCategory": "Categorie Bewerken",
    "DeleteCategory": "Categorie Verwijderen",
    "CategoryName": "Categorienaam",
    "CategoryDescription": "Beschrijving",
    "CategoryColor": "Kleur",
    "CategoryIcon": "Pictogram",
    "AllCategories": "Alle Categorieën",
    "General": "Algemeen",
    
    // Settings
    "Settings": "Instellingen",
    "UserSettings": "Gebruikersinstellingen",
    "AdminSettings": "Beheerdersinstellingen",
    "DisplaySettings": "Weergave-instellingen",
    "BehaviorSettings": "Gedragsinstellingen",
    "PerformanceSettings": "Prestatie-instellingen",
    
    // Display Options
    "DisplayMode": "Weergavemodus",
    "FlatPills": "Platte Pillen",
    "CategoryDropdowns": "Categorie Dropdowns",
    "TypeBasedDropdowns": "Type-gebaseerde Dropdowns",
    "PillStyle": "Pil Stijl",
    "Rounded": "Afgerond",
    "Square": "Vierkant",
    "Minimal": "Minimaal",
    "Density": "Dichtheid",
    "Compact": "Compact",
    "Normal": "Normaal",
    "Spacious": "Ruim",
    "ShowIcons": "Pictogrammen Tonen",
    "ShowBadges": "Badges Tonen",
    "IconSize": "Pictogramgrootte",
    "Small": "Klein",
    "Medium": "Gemiddeld",
    "Large": "Groot",
    
    // Behavior Options
    "ClickBehavior": "Klik Gedrag",
    "OpenInNewTab": "Openen in Nieuwe Tab",
    "OpenInSameTab": "Openen in Zelfde Tab",
    "OpenInPopup": "Openen in Popup",
    "SortOrder": "Sorteervolgorde",
    "Alphabetical": "Alfabetisch",
    "MostUsedFirst": "Meest Gebruikte Eerst",
    "RecentlyAddedFirst": "Recent Toegevoegde Eerst",
    "ManualOrder": "Handmatige Volgorde",
    "MaxVisibleItems": "Maximaal Zichtbare Items",
    "EnableAutoCategories": "Automatische Categorisering Inschakelen",
    "EnableQuickAdd": "Snelle Toevoeging Inschakelen",
    "EnableGlobalSearch": "Globale Zoekfunctie Inschakelen",
    "EnableHoverEffects": "Hover-effecten Inschakelen",
    "EnableKeyboardNavigation": "Toetsenbordnavigatie Inschakelen",
    
    // Storage & Sync
    "StorageSync": "Opslag en Synchronisatie",
    "OneDriveSync": "OneDrive Synchronisatie",
    "SyncFromOneDrive": "Synchroniseren vanaf OneDrive",
    "SyncToOneDrive": "Synchroniseren naar OneDrive",
    "SyncFrequency": "Synchronisatiefrequentie",
    "Realtime": "Realtime",
    "Hourly": "Elk Uur",
    "Daily": "Dagelijks",
    "ManualOnly": "Alleen Handmatig",
    "CacheDuration": "Cacheduur",
    "RecentItemsCount": "Aantal Recente Items",
    "EnableAnalytics": "Analytics Inschakelen",
    
    // Admin
    "AdminPanel": "Beheerderspaneel",
    "SharePointConfiguration": "SharePoint Configuratie",
    "BulkOperations": "Bulk Operaties",
    "AnalyticsConfiguration": "Analytics Configuratie",
    "AnalyticsDashboard": "Analytics Dashboard",
    "AudienceTargeting": "Doelgroep Targeting",
    "GlobalLinksListTitle": "Globale Linkslijst Titel",
    "EnableUserSelectionStorage": "Gebruikersselectie Opslag Inschakelen",
    "CreateGlobalLinksList": "Globale Linkslijst Aanmaken",
    "CreateUserSelectionsList": "Gebruikersselectielijst Aanmaken",
    "ValidateListsStatus": "Lijststatus Valideren",
    
    // Import/Export
    "Import": "Importeren",
    "Export": "Exporteren",
    "ImportSettings": "Instellingen Importeren",
    "ExportSettings": "Instellingen Exporteren",
    "ImportLinks": "Links Importeren",
    "ExportLinks": "Links Exporteren",
    "ResetToDefaults": "Herstellen naar Standaardinstellingen",
    "ResetAllSettings": "Alle Instellingen Resetten",
    "ValidateAllLinks": "Alle Links Valideren",
    
    // Messages
    "SettingsImportSuccess": "Instellingen succesvol geïmporteerd",
    "SettingsExportSuccess": "Instellingen succesvol geëxporteerd",
    "SettingsResetSuccess": "Instellingen hersteld naar standaardwaarden",
    "SettingsSaveSuccess": "Instellingen succesvol opgeslagen",
    "LinksImportSuccess": "Links succesvol geïmporteerd",
    "LinksExportSuccess": "Links succesvol geëxporteerd",
    "ValidationSuccess": "Validatie succesvol voltooid",
    "ValidationWarning": "Validatie voltooid met waarschuwingen",
    "ValidationError": "Validatie mislukt",
    "OperationFailed": "Operatie mislukt",
    "UnauthorizedAccess": "Ongeautoriseerde toegang",
    "NetworkError": "Netwerkfout opgetreden",
    
    // Analytics
    "TotalClicks": "Totaal Aantal Klikken",
    "UniqueUsers": "Unieke Gebruikers",
    "PopularLinks": "Populaire Links",
    "CategoryUsage": "Categoriegebruik",
    "UsageStatistics": "Gebruiksstatistieken",
    "ClickAnalytics": "Klik Analytics",
    "UserEngagement": "Gebruikersbetrokkenheid",
    "ExportAnalyticsData": "Analytics Data Exporteren",
    
    // Validation Messages
    "RequiredField": "Dit veld is verplicht",
    "InvalidUrl": "Voer een geldige URL in",
    "InvalidEmail": "Voer een geldig e-mailadres in",
    "CategoryAlreadyExists": "Categorie bestaat al",
    "LinkAlreadyExists": "Link bestaat al",
    "FieldTooLong": "Veld is te lang",
    "FieldTooShort": "Veld is te kort",
    
    // New Form Strings
    "None": "(Geen)",
    "Reset": "Resetten",
    "NewCategoryName": "Nieuwe categorienaam",
    "SubCategoryLabel": "Subcategorie (Optioneel)",
    "SubCategoryPlaceholder": "Selecteer subcategorie...",
    "NewSubCategoryName": "Nieuwe subcategorienaam",
    "CategoryLabel": "Categorie",
    
    // New Admin Strings
    "GlobalLinksListTitleLabel": "Globale Linkslijst Titel",
    "GlobalLinksListTitleDesc": "Naam van de SharePoint-lijst voor globale links",
    "OneDriveUserStorageTitle": "OneDrive Gebruikersopslag",
    "EnableUserSelectionStorageLabel": "Gebruikersselectie Opslag Inschakelen",
    "StoreInOneDrive": "Opslaan in OneDrive",
    "UseSharePointLists": "SharePoint-lijsten gebruiken",
    "UserSelectionStorageDesc": "Indien ingeschakeld, worden gebruikersselecties en voorkeuren opgeslagen als JSON-bestanden in hun OneDrive voor synchronisatie tussen apparaten.",
    "SharePointListsManagement": "SharePoint-lijstbeheer",
    "GlobalLinksListReady": "Globale Linkslijst Gereed",
    "UserSelectionsListReady": "Gebruikersselectielijst Gereed",
    "LastChecked": "Laatst gecontroleerd:",
    "GlobalLinksListFound": "Globale Linkslijst: Gevonden",
    "GlobalLinksListMissing": "Globale Linkslijst: Ontbreekt",
    "UserSelectionsListFound": "Gebruikersselectielijst: Gevonden",
    "UserSelectionsListMissing": "Gebruikersselectielijst: Ontbreekt",
    
    // Aria Labels
    "OpenUserSettingsPanelAriaLabel": "Gebruikersinstellingen paneel openen",
    "ManageLinksAriaLabel": "Persoonlijke links beheren en organisatielinks selecteren",
    
    // Dynamic Messages
    "ImportedLinksSuccess": "{0} links succesvol geïmporteerd naar SharePoint-lijst!",
    "ImportedLinksFailure": "{0} links konden niet worden geïmporteerd. Controleer de console voor details.",
    "CategoryCreatedSuccess": "Categorie \"{0}\" succesvol aangemaakt!",
    "CategoryCreationFailure": "Kon categorie niet aanmaken: {0}"
  };
});