define([], function() {
  return {
    "Title": "Samarbets-footer",
    "MyLinks": "Mina Länkar",
    "EditMyLinks": "Redigera Mina Länkar",
    "MyLinksSaveSuccess": "Mina länkar har sparats framgångsrikt",
    "MyLinksSaveFailed": "Misslyckades med att spara mina länkar",
    
    // General
    "Add": "Lägg till",
    "Edit": "Redigera",
    "Delete": "Radera",
    "Save": "Spara",
    "Cancel": "Avbryt",
    "Close": "Stäng",
    "Back": "Tillbaka",
    "Search": "Sök",
    "Loading": "Laddar...",
    "Error": "Fel",
    "Success": "Framgång",
    "Warning": "Varning",
    
    // Link Management
    "ManageLinks": "Hantera Länkar",
    "PersonalLinks": "Personliga Länkar",
    "OrganizationLinks": "Organisationslänkar",
    "AddPersonalLink": "Lägg till Personlig Länk",
    "AddOrganizationLink": "Lägg till Organisationslänk",
    "EditLink": "Redigera Länk",
    "DeleteLink": "Radera Länk",
    "LinkTitle": "Titel",
    "LinkUrl": "URL",
    "LinkDescription": "Beskrivning",
    "LinkIcon": "Ikon",
    "LinkCategory": "Kategori",
    "SearchLinks": "Sök länkar...",
    "NoLinksFound": "Inga länkar hittades",
    "LinkSaved": "Länk sparad framgångsrikt",
    "LinkDeleted": "Länk raderad framgångsrikt",
    "LinkUpdated": "Länk uppdaterad framgångsrikt",
    
    // Categories
    "Categories": "Kategorier",
    "CategoriesManagement": "Kategorihantering",
    "CreateCategory": "Skapa Kategori",
    "EditCategory": "Redigera Kategori",
    "DeleteCategory": "Radera Kategori",
    "CategoryName": "Kategorinamn",
    "CategoryDescription": "Beskrivning",
    "CategoryColor": "Färg",
    "CategoryIcon": "Ikon",
    "AllCategories": "Alla Kategorier",
    "General": "Allmänt",
    
    // Settings
    "Settings": "Inställningar",
    "UserSettings": "Användarinställningar",
    "AdminSettings": "Administratörsinställningar",
    "DisplaySettings": "Visningsinställningar",
    "BehaviorSettings": "Beteendeinställningar",
    "PerformanceSettings": "Prestationsinställningar",
    
    // Display Options
    "DisplayMode": "Visningsläge",
    "FlatPills": "Platta Piller",
    "CategoryDropdowns": "Kategori Dropdown",
    "TypeBasedDropdowns": "Typbaserade Dropdown",
    "PillStyle": "Pillstil",
    "Rounded": "Rundad",
    "Square": "Fyrkantig",
    "Minimal": "Minimal",
    "Density": "Täthet",
    "Compact": "Kompakt",
    "Normal": "Normal",
    "Spacious": "Rymlig",
    "ShowIcons": "Visa Ikoner",
    "ShowBadges": "Visa Märken",
    "IconSize": "Ikonstorlek",
    "Small": "Liten",
    "Medium": "Medium",
    "Large": "Stor",
    
    // Behavior Options
    "ClickBehavior": "Klickbeteende",
    "OpenInNewTab": "Öppna i Ny Flik",
    "OpenInSameTab": "Öppna i Samma Flik",
    "OpenInPopup": "Öppna i Popup",
    "SortOrder": "Sorteringsordning",
    "Alphabetical": "Alfabetisk",
    "MostUsedFirst": "Mest Använda Först",
    "RecentlyAddedFirst": "Senast Tillagda Först",
    "ManualOrder": "Manuell Ordning",
    "MaxVisibleItems": "Max Synliga Objekt",
    "EnableAutoCategories": "Aktivera Automatisk Kategorisering",
    "EnableQuickAdd": "Aktivera Snabbtillägg",
    "EnableGlobalSearch": "Aktivera Global Sökning",
    "EnableHoverEffects": "Aktivera Hover-effekter",
    "EnableKeyboardNavigation": "Aktivera Tangentbordsnavigering",
    
    // Storage & Sync
    "StorageSync": "Lagring och Synkronisering",
    "OneDriveSync": "OneDrive-synkronisering",
    "SyncFromOneDrive": "Synkronisera från OneDrive",
    "SyncToOneDrive": "Synkronisera till OneDrive",
    "SyncFrequency": "Synkroniseringsfrekvens",
    "Realtime": "Realtid",
    "Hourly": "Varje Timme",
    "Daily": "Dagligen",
    "ManualOnly": "Endast Manuellt",
    "CacheDuration": "Cache-varaktighet",
    "RecentItemsCount": "Antal Senaste Objekt",
    "EnableAnalytics": "Aktivera Analyser",
    
    // Admin
    "AdminPanel": "Administratörspanel",
    "SharePointConfiguration": "SharePoint-konfiguration",
    "BulkOperations": "Massoperationer",
    "AnalyticsConfiguration": "Analyskonfiguration",
    "AnalyticsDashboard": "Analysdashboard",
    "AudienceTargeting": "Målgruppsinriktning",
    "GlobalLinksListTitle": "Global Länklista Titel",
    "EnableUserSelectionStorage": "Aktivera Användarvallagring",
    "CreateGlobalLinksList": "Skapa Global Länklista",
    "CreateUserSelectionsList": "Skapa Användarvallista",
    "ValidateListsStatus": "Validera Liststatus",
    
    // Import/Export
    "Import": "Importera",
    "Export": "Exportera",
    "ImportSettings": "Importera Inställningar",
    "ExportSettings": "Exportera Inställningar",
    "ImportLinks": "Importera Länkar",
    "ExportLinks": "Exportera Länkar",
    "ResetToDefaults": "Återställ till Standard",
    "ResetAllSettings": "Återställ Alla Inställningar",
    "ValidateAllLinks": "Validera Alla Länkar",
    
    // Messages
    "SettingsImportSuccess": "Inställningar importerade framgångsrikt",
    "SettingsExportSuccess": "Inställningar exporterade framgångsrikt",
    "SettingsResetSuccess": "Inställningar återställda till standard",
    "SettingsSaveSuccess": "Inställningar sparade framgångsrikt",
    "LinksImportSuccess": "Länkar importerade framgångsrikt",
    "LinksExportSuccess": "Länkar exporterade framgångsrikt",
    "ValidationSuccess": "Validering slutförd framgångsrikt",
    "ValidationWarning": "Validering slutförd med varningar",
    "ValidationError": "Validering misslyckades",
    "OperationFailed": "Operation misslyckades",
    "UnauthorizedAccess": "Obehörig åtkomst",
    "NetworkError": "Nätverksfel inträffade",
    
    // Analytics
    "TotalClicks": "Totalt Antal Klick",
    "UniqueUsers": "Unika Användare",
    "PopularLinks": "Populära Länkar",
    "CategoryUsage": "Kategorianvändning",
    "UsageStatistics": "Användningsstatistik",
    "ClickAnalytics": "Klickanalyser",
    "UserEngagement": "Användarengagemang",
    "ExportAnalyticsData": "Exportera Analysdata",
    
    // Validation Messages
    "RequiredField": "Detta fält är obligatoriskt",
    "InvalidUrl": "Vänligen ange en giltig URL",
    "InvalidEmail": "Vänligen ange en giltig e-postadress",
    "CategoryAlreadyExists": "Kategorin finns redan",
    "LinkAlreadyExists": "Länken finns redan",
    "FieldTooLong": "Fältet är för långt",
    "FieldTooShort": "Fältet är för kort"
  };
});