define([], function() {
  return {
    "Title": "İşbirliği Alt Bilgi",
    "MyLinks": "Bağlantılarım",
    "EditMyLinks": "Bağlantılarımı Düzenle",
    "MyLinksSaveSuccess": "Bağlantılarım başarıyla kaydedildi",
    "MyLinksSaveFailed": "Bağlantılarımı kaydetme başarısız",
    
    // General
    "Add": "Ekle",
    "Edit": "Düzenle",
    "Delete": "Sil",
    "Save": "Kaydet",
    "Cancel": "İptal",
    "Close": "Kapat",
    "Back": "Geri",
    "Search": "Ara",
    "Loading": "Yükleniyor...",
    "Error": "Hata",
    "Success": "Başarılı",
    "Warning": "Uyarı",
    
    // Link Management
    "ManageLinks": "Bağlantıları Yönet",
    "PersonalLinks": "Kişisel Bağlantılar",
    "OrganizationLinks": "Organizasyon Bağlantıları",
    "AddPersonalLink": "Kişisel Bağlantı Ekle",
    "AddOrganizationLink": "Organizasyon Bağlantısı Ekle",
    "EditLink": "Bağlantıyı Düzenle",
    "DeleteLink": "Bağlantıyı Sil",
    "LinkTitle": "Başlık",
    "LinkUrl": "URL",
    "LinkDescription": "Açıklama",
    "LinkIcon": "İkon",
    "LinkCategory": "Kategori",
    "SearchLinks": "Bağlantı ara...",
    "NoLinksFound": "Hiç bağlantı bulunamadı",
    "LinkSaved": "Bağlantı başarıyla kaydedildi",
    "LinkDeleted": "Bağlantı başarıyla silindi",
    "LinkUpdated": "Bağlantı başarıyla güncellendi",
    
    // Categories
    "Categories": "Kategoriler",
    "CategoriesManagement": "Kategori Yönetimi",
    "CreateCategory": "Kategori Oluştur",
    "EditCategory": "Kategoriyi Düzenle",
    "DeleteCategory": "Kategoriyi Sil",
    "CategoryName": "Kategori Adı",
    "CategoryDescription": "Açıklama",
    "CategoryColor": "Renk",
    "CategoryIcon": "İkon",
    "AllCategories": "Tüm Kategoriler",
    "General": "Genel",
    
    // Settings
    "Settings": "Ayarlar",
    "UserSettings": "Kullanıcı Ayarları",
    "AdminSettings": "Yönetici Ayarları",
    "DisplaySettings": "Görüntü Ayarları",
    "BehaviorSettings": "Davranış Ayarları",
    "PerformanceSettings": "Performans Ayarları",
    
    // Display Options
    "DisplayMode": "Görüntü Modu",
    "FlatPills": "Düz Haplar",
    "CategoryDropdowns": "Kategori Açılır Menüleri",
    "TypeBasedDropdowns": "Tipe Dayalı Açılır Menüler",
    "PillStyle": "Hap Stili",
    "Rounded": "Yuvarlak",
    "Square": "Kare",
    "Minimal": "Minimal",
    "Density": "Yoğunluk",
    "Compact": "Kompakt",
    "Normal": "Normal",
    "Spacious": "Geniş",
    "ShowIcons": "İkonları Göster",
    "ShowBadges": "Rozetleri Göster",
    "IconSize": "İkon Boyutu",
    "Small": "Küçük",
    "Medium": "Orta",
    "Large": "Büyük",
    
    // Behavior Options
    "ClickBehavior": "Tıklama Davranışı",
    "OpenInNewTab": "Yeni Sekmede Aç",
    "OpenInSameTab": "Aynı Sekmede Aç",
    "OpenInPopup": "Popup'ta Aç",
    "SortOrder": "Sıralama Düzeni",
    "Alphabetical": "Alfabetik",
    "MostUsedFirst": "En Çok Kullanılan İlk",
    "RecentlyAddedFirst": "Son Eklenenler İlk",
    "ManualOrder": "Manuel Sıra",
    "MaxVisibleItems": "Maksimum Görünür Öğe",
    "EnableAutoCategories": "Otomatik Kategorileri Etkinleştir",
    "EnableQuickAdd": "Hızlı Ekleme Etkinleştir",
    "EnableGlobalSearch": "Global Arama Etkinleştir",
    "EnableHoverEffects": "Hover Efektlerini Etkinleştir",
    "EnableKeyboardNavigation": "Klavye Navigasyonunu Etkinleştir",
    
    // Storage & Sync
    "StorageSync": "Depolama ve Senkronizasyon",
    "OneDriveSync": "OneDrive Senkronizasyonu",
    "SyncFromOneDrive": "OneDrive'dan Senkronize Et",
    "SyncToOneDrive": "OneDrive'a Senkronize Et",
    "SyncFrequency": "Senkronizasyon Sıklığı",
    "Realtime": "Gerçek Zamanlı",
    "Hourly": "Saatlik",
    "Daily": "Günlük",
    "ManualOnly": "Sadece Manuel",
    "CacheDuration": "Önbellek Süresi",
    "RecentItemsCount": "Son Öğeler Sayısı",
    "EnableAnalytics": "Analitiği Etkinleştir",
    
    // Admin
    "AdminPanel": "Yönetici Paneli",
    "SharePointConfiguration": "SharePoint Yapılandırması",
    "BulkOperations": "Toplu İşlemler",
    "AnalyticsConfiguration": "Analitik Yapılandırması",
    "AnalyticsDashboard": "Analitik Panosu",
    "AudienceTargeting": "Kitle Hedefleme",
    "GlobalLinksListTitle": "Global Bağlantı Listesi Başlığı",
    "EnableUserSelectionStorage": "Kullanıcı Seçim Depolamasını Etkinleştir",
    "CreateGlobalLinksList": "Global Bağlantı Listesi Oluştur",
    "CreateUserSelectionsList": "Kullanıcı Seçim Listesi Oluştur",
    "ValidateListsStatus": "Liste Durumunu Doğrula",
    
    // Import/Export
    "Import": "İçe Aktar",
    "Export": "Dışa Aktar",
    "ImportSettings": "Ayarları İçe Aktar",
    "ExportSettings": "Ayarları Dışa Aktar",
    "ImportLinks": "Bağlantıları İçe Aktar",
    "ExportLinks": "Bağlantıları Dışa Aktar",
    "ResetToDefaults": "Varsayılan Değerlere Sıfırla",
    "ResetAllSettings": "Tüm Ayarları Sıfırla",
    "ValidateAllLinks": "Tüm Bağlantıları Doğrula",
    
    // Messages
    "SettingsImportSuccess": "Ayarlar başarıyla içe aktarıldı",
    "SettingsExportSuccess": "Ayarlar başarıyla dışa aktarıldı",
    "SettingsResetSuccess": "Ayarlar varsayılan değerlere sıfırlandı",
    "SettingsSaveSuccess": "Ayarlar başarıyla kaydedildi",
    "LinksImportSuccess": "Bağlantılar başarıyla içe aktarıldı",
    "LinksExportSuccess": "Bağlantılar başarıyla dışa aktarıldı",
    "ValidationSuccess": "Doğrulama başarıyla tamamlandı",
    "ValidationWarning": "Doğrulama uyarılarla tamamlandı",
    "ValidationError": "Doğrulama başarısız",
    "OperationFailed": "İşlem başarısız",
    "UnauthorizedAccess": "Yetkisiz erişim",
    "NetworkError": "Ağ hatası oluştu",
    
    // Analytics
    "TotalClicks": "Toplam Tıklama",
    "UniqueUsers": "Benzersiz Kullanıcılar",
    "PopularLinks": "Popüler Bağlantılar",
    "CategoryUsage": "Kategori Kullanımı",
    "UsageStatistics": "Kullanım İstatistikleri",
    "ClickAnalytics": "Tıklama Analitiği",
    "UserEngagement": "Kullanıcı Etkileşimi",
    "ExportAnalyticsData": "Analitik Verilerini Dışa Aktar",
    
    // Validation Messages
    "RequiredField": "Bu alan zorunludur",
    "InvalidUrl": "Lütfen geçerli bir URL girin",
    "InvalidEmail": "Lütfen geçerli bir e-posta adresi girin",
    "CategoryAlreadyExists": "Kategori zaten mevcut",
    "LinkAlreadyExists": "Bağlantı zaten mevcut",
    "FieldTooLong": "Alan çok uzun",
    "FieldTooShort": "Alan çok kısa"
  };
});